"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
import SiteHeader from "@/components/SiteHeader";
import { useLearning } from "@/components/LearningProvider";
import { hasGroundedContent, subjectCatalog } from "@/lib/curriculum";

type Message = { role: "aunty" | "student"; text: string };
const hello = "Yes beta, how can I help you today? Ask me about a concept from your Science house, and I’ll explain it using the learning material available here.";
export default function AuntyPage() {
  const { learner } = useLearning(); const [messages, setMessages] = useState<Message[]>([{ role: "aunty", text: hello }]); const [input, setInput] = useState("");
  function reply(e: FormEvent) { e.preventDefault(); const prompt = input.trim(); if (!prompt) return; setMessages(m => [...m, { role: "student", text: prompt }]); setInput(""); const available = subjectCatalog.filter(s => hasGroundedContent(learner, s)).flatMap(s => s.concepts.map(c => ({ ...c, subject: s.name, chapter: s.chapter, source: s.source }))); const lower = prompt.toLowerCase(); const match = available.find(c => c.keywords.some(k => lower.includes(k.toLowerCase())) || lower.includes(c.title.toLowerCase())); let answer = match ? `${match.title}: ${match.explanation} ${match.source ? `This comes from ${match.source.label}.` : ""}` : available.length ? `I can help with the concepts we have material for: ${available.map(c => c.title).join(", ")}. Ask me about one of those and I’ll give you a small explanation.` : "I don’t have imported curriculum material for your selected subjects yet, so I can’t give a grounded answer. When a source is added, I can help explain concepts from it."; window.setTimeout(() => setMessages(m => [...m, { role: "aunty", text: answer }]), 200); }
  return <main className="site aunty-page"><SiteHeader /><section className="aunty-page-head"><span className="mint-tag">FRIENDLY HELP, GROUNDED IN YOUR MATERIAL</span><h1>AI Aunty</h1><p>Ask for a hint or another explanation. For now, answers come from the curriculum material included in your street.</p></section><section className="chat-card"><div className="chat-heading"><span className="aunty-avatar small-avatar">✿</span><div><strong>AI Aunty</strong><small>Here to help you make sense of it</small></div><span className="online-tag">READY</span></div><div className="chat-messages" aria-live="polite">{messages.map((m,i) => <div className={`chat-bubble ${m.role}`} key={i}><span>{m.role === "aunty" ? "Aunty" : learner?.name || "You"}</span><p>{m.text}</p></div>)}</div><form className="chat-form" onSubmit={reply}><label className="sr-only" htmlFor="question">Ask AI Aunty</label><input id="question" value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask about roots, stems, leaves…" /><button aria-label="Send question">↑</button></form><small className="chat-note">AI Aunty only answers from material present in your Learning Street.</small></section><section className="quick-topics"><span className="eyebrow">A FEW PLACES TO START</span><div>{subjectCatalog[0].concepts.slice(0,4).map(c => <button key={c.id} onClick={()=>setInput(`Can you explain ${c.title.toLowerCase()}?`)}>{c.title} <span>↗</span></button>)}</div></section><Link href="/hub" className="back-to-street">← Back to your street</Link></main>;
}
